"""completed seed file for reference table and added url attr back to user, encounter, character models

Revision ID: 14fc8bdb23a0
Revises: fbffc922e0b2
Create Date: 2023-04-28 12:53:22.423337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fc8bdb23a0'
down_revision = 'fbffc922e0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('References', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.String(), nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('References', schema=None) as batch_op:
        batch_op.drop_column('class_type')

    # ### end Alembic commands ###
