"""creating db

Revision ID: 3c77843dedab
Revises: 
Create Date: 2023-04-26 18:38:03.699441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c77843dedab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('ability', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('proficiency_bonus', sa.Integer(), nullable=True),
    sa.Column('passive_perception', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('armor_class', sa.Integer(), nullable=True),
    sa.Column('hit_die', sa.Integer(), nullable=True),
    sa.Column('hit_points', sa.Integer(), nullable=True),
    sa.Column('spellcasting_ability', sa.Integer(), nullable=True),
    sa.Column('spellcasting_save', sa.Integer(), nullable=True),
    sa.Column('spellcasting_attack', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('dexterity', sa.Integer(), nullable=True),
    sa.Column('constitution', sa.Integer(), nullable=True),
    sa.Column('intelligence', sa.Integer(), nullable=True),
    sa.Column('wisdom', sa.Integer(), nullable=True),
    sa.Column('charisma', sa.Integer(), nullable=True),
    sa.Column('strength_proficiency', sa.Boolean(), nullable=True),
    sa.Column('dexterity_proficiency', sa.Boolean(), nullable=True),
    sa.Column('constitution_proficiency', sa.Boolean(), nullable=True),
    sa.Column('intelligence_proficiency', sa.Boolean(), nullable=True),
    sa.Column('wisdom_proficiency', sa.Boolean(), nullable=True),
    sa.Column('charisma_proficiency', sa.Boolean(), nullable=True),
    sa.Column('strength_saving_throw', sa.Integer(), nullable=True),
    sa.Column('dexterity_saving_throw', sa.Integer(), nullable=True),
    sa.Column('constitution_saving_throw', sa.Integer(), nullable=True),
    sa.Column('intelligence_saving_throw', sa.Integer(), nullable=True),
    sa.Column('wisdom_saving_throw', sa.Integer(), nullable=True),
    sa.Column('charisma_saving_throw', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_characters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_encounters_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_character_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('character_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_class_id'], ['character_classes.id'], name=op.f('fk_character_character_classes_character_class_id_character_classes')),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_character_classes_character_id_characters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_equipments_character_id_characters')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipments.id'], name=op.f('fk_character_equipments_equipment_id_equipments')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_features_character_id_characters')),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_character_features_feature_id_features')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_proficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('proficiency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_proficiencies_character_id_characters')),
    sa.ForeignKeyConstraint(['proficiency_id'], ['proficiencies.id'], name=op.f('fk_character_proficiencies_proficiency_id_proficiencies')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_races_character_id_characters')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_character_races_race_id_races')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_skills_character_id_characters')),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_character_skills_skill_id_skills')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_spells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_spells_character_id_characters')),
    sa.ForeignKeyConstraint(['spell_id'], ['spells.id'], name=op.f('fk_character_spells_spell_id_spells')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_subclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('subclass_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_subclasses_character_id_characters')),
    sa.ForeignKeyConstraint(['subclass_id'], ['subclasses.id'], name=op.f('fk_character_subclasses_subclass_id_subclasses')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('trait_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_traits_character_id_characters')),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], name=op.f('fk_character_traits_trait_id_traits')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encounter_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('encounter_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_encounter_characters_character_id_characters')),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_encounter_characters_encounter_id_encounters')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('encounter_characters')
    op.drop_table('character_traits')
    op.drop_table('character_subclasses')
    op.drop_table('character_spells')
    op.drop_table('character_skills')
    op.drop_table('character_races')
    op.drop_table('character_proficiencies')
    op.drop_table('character_features')
    op.drop_table('character_equipments')
    op.drop_table('character_character_classes')
    op.drop_table('encounters')
    op.drop_table('characters')
    op.drop_table('users')
    op.drop_table('traits')
    op.drop_table('subclasses')
    op.drop_table('spells')
    op.drop_table('skills')
    op.drop_table('races')
    op.drop_table('proficiencies')
    op.drop_table('features')
    op.drop_table('equipments')
    op.drop_table('character_classes')
    # ### end Alembic commands ###
