"""forgot to add db integer to spellcasting save

Revision ID: 79c3fdb5ce0b
Revises: 3c77843dedab
Create Date: 2023-04-27 15:46:17.932219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c3fdb5ce0b'
down_revision = '3c77843dedab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_die_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('hit_die_total')

    # ### end Alembic commands ###
