"""added object_id to reference table

Revision ID: 86d1e9849c73
Revises: 14fc8bdb23a0
Create Date: 2023-05-01 11:04:27.452856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86d1e9849c73'
down_revision = '14fc8bdb23a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('References', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('References', schema=None) as batch_op:
        batch_op.drop_column('object_id')

    # ### end Alembic commands ###
