"""took out url attr from user, encounter, and character classes

Revision ID: fbffc922e0b2
Revises: 29de99c6acb0
Create Date: 2023-04-28 12:24:25.221954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbffc922e0b2'
down_revision = '29de99c6acb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.drop_column('url')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('encounters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
